config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'posts#index'
  resources :posts
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  
  belongs_to :user

  validates :title, :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
  
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.includes(:user).order('created_at DESC').page(params[:page]).per(10)
  end

  def new
    @post = Post.new
  end

  def create
    Post.create(post_params)
    redirect_to root_path
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    post = Post.find(params[:id])
    post.update(post_params)
    redirect_to post_path(post)
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to root_path
  end

  private

  def post_params
    params.require(:post).permit(:title, :content).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order("created_at DESC").page(params[:page]).per(10)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title BlogApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/posts/_header.html.haml
.header
  .header__left-navi
    = link_to 'Our Blog', root_path, class: 'header__left-navi__text'
  - if user_signed_in?
    .header__right-navi
      = link_to '新規投稿', new_post_path, class: 'header__right-navi__box', id: 'new-posts'
      = link_to "#{current_user.name}", user_path(current_user.id), class: 'header__right-navi__box'
      = link_to 'ログアウト', destroy_user_session_path, method: :delete, class: 'header__right-navi__box'
  - else
    .header__right-navi
      = link_to '新規登録', new_user_registration_path, class: 'header__right-navi__box'
      = link_to 'ログイン', new_user_session_path, class: 'header__right-navi__box'

app/views/posts/edit.html.haml
.wrapper
  = render partial: 'header'
  .content
    %h2 投稿記事の編集
    = form_with model: @post, class: 'form', local: true do |f|
      .content__top
        = f.text_field :title, autoforcus: true, placeholder: 'タイトル', class: 'form__title'
      .content__middle
        = f.text_area :content, autoforcus: true, placeholder: '本文', class: 'form__text'
      .content__bottom
        = f.submit '編集する', class: 'form__submit'
  .footer

app/views/posts/index.html.haml
.wrapper
  = render partial: 'header'
  .main-content
    %h2 最新記事一覧
    - @posts.each do |post|
      .main-content__article
        = link_to "■【#{post.title}】", post_path(post), class: 'main-content__article__detail'
        = link_to "投稿者：#{post.user.name}", user_path(post.user), class: 'main-content__article__detail-name'
  %ul
    %li=paginate(@posts)
  .footer

app/views/posts/new.html.haml
.wrapper
  = render partial: 'header'
  .content
    %h2 新規記事作成
    = form_with model: @post, class: 'form', local: true do |f|
      .content__top
        = f.text_field :title, autoforcus: true, placeholder: 'タイトル', class: 'form__title'
      .content__middle
        = f.text_area :content, autoforcus: true, placeholder: '本文', class: 'form__text'
      .content__bottom
        = f.submit '投稿する', class: 'form__submit'

app/views/posts/show.html.haml
.wrapper
  = render partial: 'header'
  .show
    .show__title
      %h2= @post.title
    .show__content
      %p= simple_format(@post.content)
    .show__bottom
    - if user_signed_in? && @post.user_id == current_user.id
      = link_to '編集', edit_post_path(@post), class: 'show__bottom__text'
      = link_to '削除', post_path(@post), method: :delete, data: {confirm: "削除しますか？"}, class: 'show__bottom__text'
      = link_to '記事一覧に戻る', root_path, class: 'show__bottom__text'
    - else
      = link_to '記事一覧に戻る', root_path, class: 'show__bottom__text'

app/views/users/show.html.haml
.wrapper
  = render partial: 'posts/header'
  .main-content
    %h2 #{@user.name}の記事一覧
    - @posts.each do |post|
      .main-content__article
        = link_to "■【#{post.title}】", post_path(post), class: 'main-content__article__detail'
  %ul
    %li=paginate(@posts)
  .footer